# Generated by Django 3.1.7 on 2021-03-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_auto_20210324_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
