# Generated by Django 3.1.7 on 2021-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20210305_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(max_length=100),
        ),
    ]
