# Generated by Django 3.1.7 on 2021-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20210305_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
